name: Generate YouTube Links

on:
  push:
    paths:
      - 'metadata.json'
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install yt-dlp requests

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Generate YouTube links
        run: |
          python scripts/fetch_youtube_links.py
